services:
 postgres:
  image: postgres:15
  container_name: contact-postgres
  restart: always
  environment:
    POSTGRES_DB: contactdb
    POSTGRES_USER: user
    POSTGRES_PASSWORD: password
  ports:
    - "5432:5432"
    